### ISSUE TITLE
DID document issue when one node is unavailable

### ISSUE THREAD

**Issue by nick-verida** [verida/storage-node#59]
In a 3 node setup, if one node becomes unavailable we see the following behaviour:

```
Adding DID document to cache: did:vda:testnet:0x6bf00d67fd4dc2f66a801badd9b584a48c6db283
(node:8) UnhandledPromiseRejectionWarning: Error: deleted
    at Request._callback (/storage-node/node_modules/nano/lib/nano.js:168:15)
    at Request.self.callback (/storage-node/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/storage-node/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/storage-node/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
(node:8) Error: deleted
    at Request._callback (/storage-node/node_modules/nano/lib/nano.js:168:15)
    at Request.self.callback (/storage-node/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/storage-node/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/storage-node/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
DID document not in cache: did:vda:testnet:0x6bf00d67fd4dc2f66a801badd9b584a48c6db283, fetching
Adding DID document to cache: did:vda:testnet:0x6bf00d67fd4dc2f66a801badd9b584a48c6db283
Unable to verify credentials from https://node1-euw6.gcp.acacia.verida.tech (Unable to update password: Document update conflict.})
```

and 

```
DID document not in cache: did:vda:testnet:0xc7979deb3495d2eeb56f92f485f56d29eaf7b5ee, fetching
Adding DID document to cache: did:vda:testnet:0xc7979deb3495d2eeb56f92f485f56d29eaf7b5ee
https://node3-euw6.gcp.acacia.verida.tech:443: Error saving replication entry for https://node1-euw6.gcp.acacia.verida.tech (e8b2255aabd00dc5d61aa7a583c8678fa9bdb7a4a16a7a49979c8f1e3792c38e9): Document update conflict.
Unable to create replication entry: Document update conflict.
```

@tahpot says:

> This error occurs when node 2 and 3 are trying to talk to node 1 to setup replication. This seems like an edge case where node 2 and 3 are getting an unexpected error from node 1 and not gracefully logging and ignoring (as it's assumed nodes may come up and down from time to time).

Note that (I assume) we have to be very careful to make sure that the record has been replicated to at least one node before assuming it is a single node outage. Otherwise the node we are on could be the one that is desynchronized from the other 2 nodes somehow.

**Comment by tahpot** [comment]
This appears to be resolved as DID documents and connections are working fine when 1/3 node is down.
